In [1]:
json_data = !curl --data 'query= {"terms":[{"type":"string","term":"status_group","in_list":["paying"]}],"count":1000,"offset":0,"fields":[{"type":"string","term":"health","field_display_name":"Health rank"},{"type":"simple_date_attribute","attribute":"Contract Renewal Date","field_display_name":"Contract Renewal Date"},{"type":"simple_date_attribute","attribute":"Next QBR Date","field_display_name":"Next EBR Date"}],"scope":"all"}' --header 'app-token:{bcrypt}$2a$10$YGdidafKcBSKDRq/ZTJAcezgnKuFruviQ5r6znEc/pwmwbnCWjpDe' 'https://api-eu1.totango.com/api/v1/search/accounts'

In [2]:
json_data

['{"took":18,"_revision":"r126a6ea","response":{"accounts":{"hits":[{"name":"8972745897","display_name":"Lights On Staffing","selected_fields":["red","2022-09-01","2022-09-15"]},{"name":"6806348329","display_name":"Eci-Rx","selected_fields":["green","2022-10-11","2022-10-27"]},{"name":"6053112603","display_name":"Amicus Recruitment","selected_fields":["green","2023-05-11","2022-10-31"]},{"name":"5339057664","display_name":"Notion","selected_fields":["red","2022-11-03","2022-10-10"]},{"name":"4763084213","display_name":"Amazon Market Intelligence","selected_fields":["green","2022-12-30",null]},{"name":"3881453684","display_name":"Clubspeed","selected_fields":["red","2023-04-21",null]},{"name":"2835412967","display_name":"Automattic","selected_fields":["green","2023-07-23","2022-12-22"]},{"name":"2481999156","display_name":"Vera Whole Health","selected_fields":["green","2022-12-04","2022-10-19"]},{"name":"1889716994","display_name":"Cisco Global","selected_fields":["green","2023-05-01","2023-01-04"]},{"name":"1880536529","display_name":"Gopuff","selected_fields":["green","2023-07-13","2022-12-06"]},{"name":"1268102635","display_name":"InBev","selected_fields":["green","2023-05-17","2022-10-27"]},{"name":"5146554028","display_name":"Network Partners","selected_fields":["green","2023-02-01","2022-12-14"]},{"name":"986704637","display_name":"Brex","selected_fields":["yellow","2022-12-31","2022-11-01"]},{"name":"6441984831","display_name":"Treasure Data","selected_fields":["red","2023-02-06","2022-12-20"]},{"name":"1077723458","display_name":"Snap","selected_fields":["yellow","2023-03-22","2022-11-16"]},{"name":"871372820","display_name":"Epic Games","selected_fields":["red","2022-10-24","2022-10-05"]},{"name":"709994097","display_name":"DoorDash","selected_fields":["green","2023-12-01","2022-12-14"]},{"name":"696994280","display_name":"Virta Health","selected_fields":["green","2023-02-12","2022-11-16"]},{"name":"695760844","display_name":"Roche","selected_fields":["green","2024-08-01","2022-10-05"]},{"name":"690169075","display_name":"Dropbox","selected_fields":["green","2022-12-31","2022-12-01"]},{"name":"4059715357","display_name":"Intercom","selected_fields":["red","2022-10-27","2022-09-28"]},{"name":"525687177","display_name":"Amazon Executive Recruiting","selected_fields":["green","2023-06-22","2022-09-14"]},{"name":"512258368","display_name":"Checkr","selected_fields":["green","2023-05-03","2022-10-31"]},{"name":"474687556","display_name":"Respawn Entertainment","selected_fields":["red","2022-10-13","2022-10-03"]},{"name":"242908228","display_name":"BridgeView","selected_fields":["green","2023-09-20","2022-10-10"]},{"name":"242908103","display_name":"Genentech","selected_fields":["yellow","2024-08-01","2022-11-01"]},{"name":"242907783","display_name":"Validant Engage","selected_fields":["green","2024-04-18","2022-11-23"]},{"name":"242907563","display_name":"Sonos","selected_fields":["red","2022-11-22","2022-10-26"]}],"stats":{},"total_hits":28}},"service_id":"52222","_type":"status","_version":1,"status":"success"}']

In [3]:
import json

In [4]:
json_data1 = json.loads(json_data[0])

In [5]:
json_data1['response']

{'accounts': {'hits': [{'name': '8972745897',
    'display_name': 'Lights On Staffing',
    'selected_fields': ['red', '2022-09-01', '2022-09-15']},
   {'name': '6806348329',
    'display_name': 'Eci-Rx',
    'selected_fields': ['green', '2022-10-11', '2022-10-27']},
   {'name': '6053112603',
    'display_name': 'Amicus Recruitment',
    'selected_fields': ['green', '2023-05-11', '2022-10-31']},
   {'name': '5339057664',
    'display_name': 'Notion',
    'selected_fields': ['red', '2022-11-03', '2022-10-10']},
   {'name': '4763084213',
    'display_name': 'Amazon Market Intelligence',
    'selected_fields': ['green', '2022-12-30', None]},
   {'name': '3881453684',
    'display_name': 'Clubspeed',
    'selected_fields': ['red', '2023-04-21', None]},
   {'name': '2835412967',
    'display_name': 'Automattic',
    'selected_fields': ['green', '2023-07-23', '2022-12-22']},
   {'name': '2481999156',
    'display_name': 'Vera Whole Health',
    'selected_fields': ['green', '2022-12-04', '2022-10-19']},
   {'name': '1889716994',
    'display_name': 'Cisco Global',
    'selected_fields': ['green', '2023-05-01', '2023-01-04']},
   {'name': '1880536529',
    'display_name': 'Gopuff',
    'selected_fields': ['green', '2023-07-13', '2022-12-06']},
   {'name': '1268102635',
    'display_name': 'InBev',
    'selected_fields': ['green', '2023-05-17', '2022-10-27']},
   {'name': '5146554028',
    'display_name': 'Network Partners',
    'selected_fields': ['green', '2023-02-01', '2022-12-14']},
   {'name': '986704637',
    'display_name': 'Brex',
    'selected_fields': ['yellow', '2022-12-31', '2022-11-01']},
   {'name': '6441984831',
    'display_name': 'Treasure Data',
    'selected_fields': ['red', '2023-02-06', '2022-12-20']},
   {'name': '1077723458',
    'display_name': 'Snap',
    'selected_fields': ['yellow', '2023-03-22', '2022-11-16']},
   {'name': '871372820',
    'display_name': 'Epic Games',
    'selected_fields': ['red', '2022-10-24', '2022-10-05']},
   {'name': '709994097',
    'display_name': 'DoorDash',
    'selected_fields': ['green', '2023-12-01', '2022-12-14']},
   {'name': '696994280',
    'display_name': 'Virta Health',
    'selected_fields': ['green', '2023-02-12', '2022-11-16']},
   {'name': '695760844',
    'display_name': 'Roche',
    'selected_fields': ['green', '2024-08-01', '2022-10-05']},
   {'name': '690169075',
    'display_name': 'Dropbox',
    'selected_fields': ['green', '2022-12-31', '2022-12-01']},
   {'name': '4059715357',
    'display_name': 'Intercom',
    'selected_fields': ['red', '2022-10-27', '2022-09-28']},
   {'name': '525687177',
    'display_name': 'Amazon Executive Recruiting',
    'selected_fields': ['green', '2023-06-22', '2022-09-14']},
   {'name': '512258368',
    'display_name': 'Checkr',
    'selected_fields': ['green', '2023-05-03', '2022-10-31']},
   {'name': '474687556',
    'display_name': 'Respawn Entertainment',
    'selected_fields': ['red', '2022-10-13', '2022-10-03']},
   {'name': '242908228',
    'display_name': 'BridgeView',
    'selected_fields': ['green', '2023-09-20', '2022-10-10']},
   {'name': '242908103',
    'display_name': 'Genentech',
    'selected_fields': ['yellow', '2024-08-01', '2022-11-01']},
   {'name': '242907783',
    'display_name': 'Validant Engage',
    'selected_fields': ['green', '2024-04-18', '2022-11-23']},
   {'name': '242907563',
    'display_name': 'Sonos',
    'selected_fields': ['red', '2022-11-22', '2022-10-26']}],
  'stats': {},
  'total_hits': 28}}

In [6]:
import pandas as pd

In [7]:
df2 = pd.json_normalize(json_data1)

In [8]:
df2

,took,_revision,service_id,_type,_version,status,response.accounts.hits,response.accounts.total_hits
0,18,r126a6ea,52222,status,1,success,"[{'name': '8972745897', 'display_name': 'Light...",28

In [9]:
test = df2['response.accounts.hits'].to_json()

In [10]:
type(test)

str

In [11]:
test

'{"0":[{"name":"8972745897","display_name":"Lights On Staffing","selected_fields":["red","2022-09-01","2022-09-15"]},{"name":"6806348329","display_name":"Eci-Rx","selected_fields":["green","2022-10-11","2022-10-27"]},{"name":"6053112603","display_name":"Amicus Recruitment","selected_fields":["green","2023-05-11","2022-10-31"]},{"name":"5339057664","display_name":"Notion","selected_fields":["red","2022-11-03","2022-10-10"]},{"name":"4763084213","display_name":"Amazon Market Intelligence","selected_fields":["green","2022-12-30",null]},{"name":"3881453684","display_name":"Clubspeed","selected_fields":["red","2023-04-21",null]},{"name":"2835412967","display_name":"Automattic","selected_fields":["green","2023-07-23","2022-12-22"]},{"name":"2481999156","display_name":"Vera Whole Health","selected_fields":["green","2022-12-04","2022-10-19"]},{"name":"1889716994","display_name":"Cisco Global","selected_fields":["green","2023-05-01","2023-01-04"]},{"name":"1880536529","display_name":"Gopuff","selected_fields":["green","2023-07-13","2022-12-06"]},{"name":"1268102635","display_name":"InBev","selected_fields":["green","2023-05-17","2022-10-27"]},{"name":"5146554028","display_name":"Network Partners","selected_fields":["green","2023-02-01","2022-12-14"]},{"name":"986704637","display_name":"Brex","selected_fields":["yellow","2022-12-31","2022-11-01"]},{"name":"6441984831","display_name":"Treasure Data","selected_fields":["red","2023-02-06","2022-12-20"]},{"name":"1077723458","display_name":"Snap","selected_fields":["yellow","2023-03-22","2022-11-16"]},{"name":"871372820","display_name":"Epic Games","selected_fields":["red","2022-10-24","2022-10-05"]},{"name":"709994097","display_name":"DoorDash","selected_fields":["green","2023-12-01","2022-12-14"]},{"name":"696994280","display_name":"Virta Health","selected_fields":["green","2023-02-12","2022-11-16"]},{"name":"695760844","display_name":"Roche","selected_fields":["green","2024-08-01","2022-10-05"]},{"name":"690169075","display_name":"Dropbox","selected_fields":["green","2022-12-31","2022-12-01"]},{"name":"4059715357","display_name":"Intercom","selected_fields":["red","2022-10-27","2022-09-28"]},{"name":"525687177","display_name":"Amazon Executive Recruiting","selected_fields":["green","2023-06-22","2022-09-14"]},{"name":"512258368","display_name":"Checkr","selected_fields":["green","2023-05-03","2022-10-31"]},{"name":"474687556","display_name":"Respawn Entertainment","selected_fields":["red","2022-10-13","2022-10-03"]},{"name":"242908228","display_name":"BridgeView","selected_fields":["green","2023-09-20","2022-10-10"]},{"name":"242908103","display_name":"Genentech","selected_fields":["yellow","2024-08-01","2022-11-01"]},{"name":"242907783","display_name":"Validant Engage","selected_fields":["green","2024-04-18","2022-11-23"]},{"name":"242907563","display_name":"Sonos","selected_fields":["red","2022-11-22","2022-10-26"]}]}'

In [12]:
test2 = json.loads(test)

In [13]:
test2

{'0': [{'name': '8972745897',
   'display_name': 'Lights On Staffing',
   'selected_fields': ['red', '2022-09-01', '2022-09-15']},
  {'name': '6806348329',
   'display_name': 'Eci-Rx',
   'selected_fields': ['green', '2022-10-11', '2022-10-27']},
  {'name': '6053112603',
   'display_name': 'Amicus Recruitment',
   'selected_fields': ['green', '2023-05-11', '2022-10-31']},
  {'name': '5339057664',
   'display_name': 'Notion',
   'selected_fields': ['red', '2022-11-03', '2022-10-10']},
  {'name': '4763084213',
   'display_name': 'Amazon Market Intelligence',
   'selected_fields': ['green', '2022-12-30', None]},
  {'name': '3881453684',
   'display_name': 'Clubspeed',
   'selected_fields': ['red', '2023-04-21', None]},
  {'name': '2835412967',
   'display_name': 'Automattic',
   'selected_fields': ['green', '2023-07-23', '2022-12-22']},
  {'name': '2481999156',
   'display_name': 'Vera Whole Health',
   'selected_fields': ['green', '2022-12-04', '2022-10-19']},
  {'name': '1889716994',
   'display_name': 'Cisco Global',
   'selected_fields': ['green', '2023-05-01', '2023-01-04']},
  {'name': '1880536529',
   'display_name': 'Gopuff',
   'selected_fields': ['green', '2023-07-13', '2022-12-06']},
  {'name': '1268102635',
   'display_name': 'InBev',
   'selected_fields': ['green', '2023-05-17', '2022-10-27']},
  {'name': '5146554028',
   'display_name': 'Network Partners',
   'selected_fields': ['green', '2023-02-01', '2022-12-14']},
  {'name': '986704637',
   'display_name': 'Brex',
   'selected_fields': ['yellow', '2022-12-31', '2022-11-01']},
  {'name': '6441984831',
   'display_name': 'Treasure Data',
   'selected_fields': ['red', '2023-02-06', '2022-12-20']},
  {'name': '1077723458',
   'display_name': 'Snap',
   'selected_fields': ['yellow', '2023-03-22', '2022-11-16']},
  {'name': '871372820',
   'display_name': 'Epic Games',
   'selected_fields': ['red', '2022-10-24', '2022-10-05']},
  {'name': '709994097',
   'display_name': 'DoorDash',
   'selected_fields': ['green', '2023-12-01', '2022-12-14']},
  {'name': '696994280',
   'display_name': 'Virta Health',
   'selected_fields': ['green', '2023-02-12', '2022-11-16']},
  {'name': '695760844',
   'display_name': 'Roche',
   'selected_fields': ['green', '2024-08-01', '2022-10-05']},
  {'name': '690169075',
   'display_name': 'Dropbox',
   'selected_fields': ['green', '2022-12-31', '2022-12-01']},
  {'name': '4059715357',
   'display_name': 'Intercom',
   'selected_fields': ['red', '2022-10-27', '2022-09-28']},
  {'name': '525687177',
   'display_name': 'Amazon Executive Recruiting',
   'selected_fields': ['green', '2023-06-22', '2022-09-14']},
  {'name': '512258368',
   'display_name': 'Checkr',
   'selected_fields': ['green', '2023-05-03', '2022-10-31']},
  {'name': '474687556',
   'display_name': 'Respawn Entertainment',
   'selected_fields': ['red', '2022-10-13', '2022-10-03']},
  {'name': '242908228',
   'display_name': 'BridgeView',
   'selected_fields': ['green', '2023-09-20', '2022-10-10']},
  {'name': '242908103',
   'display_name': 'Genentech',
   'selected_fields': ['yellow', '2024-08-01', '2022-11-01']},
  {'name': '242907783',
   'display_name': 'Validant Engage',
   'selected_fields': ['green', '2024-04-18', '2022-11-23']},
  {'name': '242907563',
   'display_name': 'Sonos',
   'selected_fields': ['red', '2022-11-22', '2022-10-26']}]}

In [14]:
test2['0'][1]

{'name': '6806348329',
 'display_name': 'Eci-Rx',
 'selected_fields': ['green', '2022-10-11', '2022-10-27']}

# New section

In [15]:
test_df = pd.json_normalize(test2['0'])

In [16]:
test_df

          name                 display_name                   selected_fields
0   8972745897           Lights On Staffing     [red, 2022-09-01, 2022-09-15]
1   6806348329                       Eci-Rx   [green, 2022-10-11, 2022-10-27]
2   6053112603           Amicus Recruitment   [green, 2023-05-11, 2022-10-31]
3   5339057664                       Notion     [red, 2022-11-03, 2022-10-10]
4   4763084213   Amazon Market Intelligence         [green, 2022-12-30, None]
5   3881453684                    Clubspeed           [red, 2023-04-21, None]
6   2835412967                   Automattic   [green, 2023-07-23, 2022-12-22]
7   2481999156            Vera Whole Health   [green, 2022-12-04, 2022-10-19]
8   1889716994                 Cisco Global   [green, 2023-05-01, 2023-01-04]
9   1880536529                       Gopuff   [green, 2023-07-13, 2022-12-06]
10  1268102635                        InBev   [green, 2023-05-17, 2022-10-27]
11  5146554028             Network Partners   [green, 2023-02-01, 2022-12-14]
12   986704637                         Brex  [yellow, 2022-12-31, 2022-11-01]
13  6441984831                Treasure Data     [red, 2023-02-06, 2022-12-20]
14  1077723458                         Snap  [yellow, 2023-03-22, 2022-11-16]
15   871372820                   Epic Games     [red, 2022-10-24, 2022-10-05]
16   709994097                     DoorDash   [green, 2023-12-01, 2022-12-14]
17   696994280                 Virta Health   [green, 2023-02-12, 2022-11-16]
18   695760844                        Roche   [green, 2024-08-01, 2022-10-05]
19   690169075                      Dropbox   [green, 2022-12-31, 2022-12-01]
20  4059715357                     Intercom     [red, 2022-10-27, 2022-09-28]
21   525687177  Amazon Executive Recruiting   [green, 2023-06-22, 2022-09-14]
22   512258368                       Checkr   [green, 2023-05-03, 2022-10-31]
23   474687556        Respawn Entertainment     [red, 2022-10-13, 2022-10-03]
24   242908228                   BridgeView   [green, 2023-09-20, 2022-10-10]
25   242908103                    Genentech  [yellow, 2024-08-01, 2022-11-01]
26   242907783              Validant Engage   [green, 2024-04-18, 2022-11-23]
27   242907563                        Sonos     [red, 2022-11-22, 2022-10-26]

In [17]:
display_name = test_df['display_name']

In [18]:
display_name

0              Lights On Staffing
1                          Eci-Rx
2              Amicus Recruitment
3                          Notion
4      Amazon Market Intelligence
5                       Clubspeed
6                      Automattic
7               Vera Whole Health
8                    Cisco Global
9                          Gopuff
10                          InBev
11               Network Partners
12                           Brex
13                  Treasure Data
14                           Snap
15                     Epic Games
16                       DoorDash
17                   Virta Health
18                          Roche
19                        Dropbox
20                       Intercom
21    Amazon Executive Recruiting
22                         Checkr
23          Respawn Entertainment
24                     BridgeView
25                      Genentech
26                Validant Engage
27                          Sonos
Name: display_name, dtype: object

In [19]:
df3 = pd.DataFrame(test_df['selected_fields'].to_list(), columns=['Health_Rank','Contract_renewal_date','Next_EBR_date'])

In [20]:
df3

   Health_Rank Contract_renewal_date Next_EBR_date
0          red            2022-09-01    2022-09-15
1        green            2022-10-11    2022-10-27
2        green            2023-05-11    2022-10-31
3          red            2022-11-03    2022-10-10
4        green            2022-12-30          None
5          red            2023-04-21          None
6        green            2023-07-23    2022-12-22
7        green            2022-12-04    2022-10-19
8        green            2023-05-01    2023-01-04
9        green            2023-07-13    2022-12-06
10       green            2023-05-17    2022-10-27
11       green            2023-02-01    2022-12-14
12      yellow            2022-12-31    2022-11-01
13         red            2023-02-06    2022-12-20
14      yellow            2023-03-22    2022-11-16
15         red            2022-10-24    2022-10-05
16       green            2023-12-01    2022-12-14
17       green            2023-02-12    2022-11-16
18       green            2024-08-01    2022-10-05
19       green            2022-12-31    2022-12-01
20         red            2022-10-27    2022-09-28
21       green            2023-06-22    2022-09-14
22       green            2023-05-03    2022-10-31
23         red            2022-10-13    2022-10-03
24       green            2023-09-20    2022-10-10
25      yellow            2024-08-01    2022-11-01
26       green            2024-04-18    2022-11-23
27         red            2022-11-22    2022-10-26

In [21]:
df3['display_name'] = display_name

In [24]:
df3

,Health_Rank,Contract_renewal_date,Next_EBR_date,display_name
0,red,2022-09-01,2022-09-15,Lights On Staffing
1,green,2022-10-11,2022-10-27,Eci-Rx
2,green,2023-05-11,2022-10-31,Amicus Recruitment
3,red,2022-11-03,2022-10-10,Notion
4,green,2022-12-30,None,Amazon Market Intelligence
5,red,2023-04-21,None,Clubspeed
6,green,2023-07-23,2022-12-22,Automattic
7,green,2022-12-04,2022-10-19,Vera Whole Health
8,green,2023-05-01,2023-01-04,Cisco Global
9,green,2023-07-13,2022-12-06,Gopuff
10,green,2023-05-17,2022-10-27,InBev
11,green,2023-02-01,2022-12-14,Network Partners
12,yellow,2022-12-31,2022-11-01,Brex
13,red,2023-02-06,2022-12-20,Treasure Data
14,yellow,2023-03-22,2022-11-16,Snap
15,red,2022-10-24,2022-10-05,Epic Games
16,green,2023-12-01,2022-12-14,DoorDash
17,green,2023-02-12,2022-11-16,Virta Health
18,green,2024-08-01,2022-10-05,Roche
19,green,2022-12-31,2022-12-01,Dropbox
20,red,2022-10-27,2022-09-28,Intercom
21,green,2023-06-22,2022-09-14,Amazon Executive Recruiting
22,green,2023-05-03,2022-10-31,Checkr
23,red,2022-10-13,2022-10-03,Respawn Entertainment
24,green,2023-09-20,2022-10-10,BridgeView
25,yellow,2024-08-01,2022-11-01,Genentech
26,green,2024-04-18,2022-11-23,Validant Engage
27,red,2022-11-22,2022-10-26,Sonos

In [25]:
def f(x):
  if x['Health_Rank'] == 'red': return 'poor'
  elif x['Health_Rank'] == 'green': return 'healthy'
  else: return 'average'

In [26]:
df3['Health_Rank'] = df3.apply(f, axis=1)

In [27]:
df3

,Health_Rank,Contract_renewal_date,Next_EBR_date,display_name
0,poor,2022-09-01,2022-09-15,Lights On Staffing
1,healthy,2022-10-11,2022-10-27,Eci-Rx
2,healthy,2023-05-11,2022-10-31,Amicus Recruitment
3,poor,2022-11-03,2022-10-10,Notion
4,healthy,2022-12-30,None,Amazon Market Intelligence
5,poor,2023-04-21,None,Clubspeed
6,healthy,2023-07-23,2022-12-22,Automattic
7,healthy,2022-12-04,2022-10-19,Vera Whole Health
8,healthy,2023-05-01,2023-01-04,Cisco Global
9,healthy,2023-07-13,2022-12-06,Gopuff
10,healthy,2023-05-17,2022-10-27,InBev
11,healthy,2023-02-01,2022-12-14,Network Partners
12,average,2022-12-31,2022-11-01,Brex
13,poor,2023-02-06,2022-12-20,Treasure Data
14,average,2023-03-22,2022-11-16,Snap
15,poor,2022-10-24,2022-10-05,Epic Games
16,healthy,2023-12-01,2022-12-14,DoorDash
17,healthy,2023-02-12,2022-11-16,Virta Health
18,healthy,2024-08-01,2022-10-05,Roche
19,healthy,2022-12-31,2022-12-01,Dropbox
20,poor,2022-10-27,2022-09-28,Intercom
21,healthy,2023-06-22,2022-09-14,Amazon Executive Recruiting
22,healthy,2023-05-03,2022-10-31,Checkr
23,poor,2022-10-13,2022-10-03,Respawn Entertainment
24,healthy,2023-09-20,2022-10-10,BridgeView
25,average,2024-08-01,2022-11-01,Genentech
26,healthy,2024-04-18,2022-11-23,Validant Engage
27,poor,2022-11-22,2022-10-26,Sonos